"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { fetchPublicCheatsheet } from "@/lib/api";
import type { PublicCheatsheetDetail } from "@/lib/api";
import { CheatsheetContent } from "@/components/cheatsheet/cheatsheet-content";
import type { CheatsheetResponse } from "@/types/cheatsheet";

export default function SharedCheatsheetPage() {
  const params = useParams();
  const id = params.id as string;

  const [data, setData] = useState<PublicCheatsheetDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!id) return;
    fetchPublicCheatsheet(id)
      .then(setData)
      .catch(() => setError("Cheatsheet not found or is private"))
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) {
    return (
      <div className="mx-auto max-w-4xl px-6 py-12">
        <div className="animate-pulse space-y-6">
          <div className="h-8 w-64 rounded bg-surface-high" />
          <div className="h-96 rounded-lg bg-surface-high" />
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="mx-auto max-w-4xl px-6 py-20 text-center">
        <h1 className="font-display text-2xl font-bold text-on-surface">
          Cheatsheet Not Found
        </h1>
        <p className="mt-2 text-sm text-on-surface-muted">
          This cheatsheet doesn&apos;t exist or is private.
        </p>
        <Link
          href="/pokemon"
          className="mt-6 inline-block btn-primary px-6 py-2 font-display text-xs uppercase tracking-wider"
        >
          Browse Pokedex
        </Link>
      </div>
    );
  }

  const cs = data.cheatsheet_json as CheatsheetResponse;
  const displayName = data.owner_display_name || data.owner_username || "Trainer";

  return (
    <div className="mx-auto max-w-4xl px-6 py-12">
      {/* Header */}
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="font-display text-2xl font-bold tracking-tight text-on-surface">
            {data.team_name || cs.team_title}
          </h1>
          <div className="mt-1 flex items-center gap-3">
            {data.team_format && (
              <span className="rounded-full bg-surface-high px-2 py-0.5 font-display text-[0.55rem] uppercase tracking-wider text-on-surface-muted">
                {data.team_format}
              </span>
            )}
            <span className="text-xs text-on-surface-muted">
              {new Date(data.updated_at).toLocaleDateString()}
            </span>
          </div>
        </div>

        {/* Owner info */}
        {data.owner_username && (
          <Link
            href={`/u/${data.owner_username}`}
            className="flex items-center gap-2 rounded-lg border border-outline-variant px-3 py-2 transition-colors hover:bg-surface-mid/30"
          >
            {data.owner_avatar_sprite_url ? (
              <Image
                src={data.owner_avatar_sprite_url}
                alt={displayName}
                width={24}
                height={24}
                className="image-rendering-pixelated"
                unoptimized
              />
            ) : (
              <span className="flex h-6 w-6 items-center justify-center rounded-full bg-surface-high font-display text-xs text-on-surface-muted">
                {displayName[0]?.toUpperCase()}
              </span>
            )}
            <span className="text-xs text-on-surface-muted">
              @{data.owner_username}
            </span>
          </Link>
        )}
      </div>

      {/* Cheatsheet content */}
      <div className="rounded-[1rem] border border-outline-variant bg-surface-low p-5">
        <CheatsheetContent data={cs} />
      </div>

      {/* Attribution */}
      <div className="mt-6 text-center">
        <p className="text-xs text-on-surface-muted">
          Generated by{" "}
          <Link href="/" className="text-primary hover:underline">
            PokeComp
          </Link>{" "}
          -- AI-powered Pokemon Champions companion
        </p>
      </div>
    </div>
  );
}
